<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SG.HealthChecks.UI.InMemory.Storage</PackageId>
    <TargetFramework>net10.0</TargetFramework>
    <PackageTags>$(PackageTags);InMemory</PackageTags>
    <Description>HealthChecks.UI.InMemory.Storage package contains the required classes to use InMemory provider in the UI</Description>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
 

  <ItemGroup>
    <ProjectReference Include="..\HealthChecks.UI.Data\HealthChecks.UI.Data.csproj" />
  </ItemGroup>

</Project>

