<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SG.HealthChecks.SqlServer</PackageId>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <PackageTags>$(PackageTags);Sql Server</PackageTags>
    <Description>HealthChecks.SqlServer is the health check package for SqlServer.</Description>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>

